import React, { useState, useEffect } from 'react';
import { CompanyConfig, Product } from '../types';
import { supabase } from '../lib/supabase';
import { LOGO_URL } from '../constants';
import { syncProductsFromOdoo } from '../services/odooService';

interface AdminPanelProps {
  onClose: () => void;
  config: CompanyConfig | null;
  products: Product[];
  onRefresh: () => void;
}

export const AdminPanel: React.FC<AdminPanelProps> = ({ onClose, config, products, onRefresh }) => {
  const [activeTab, setActiveTab] = useState<'config' | 'odoo' | 'orders' | 'help'>('config');
  const [formData, setFormData] = useState<any>(config || { banners: [] });
  const [orders, setOrders] = useState<any[]>([]);
  const [isSaving, setIsSaving] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);
  const [syncStatus, setSyncStatus] = useState<{msg: string, type: 'success' | 'error' | 'none'}>({msg: '', type: 'none'});

  useEffect(() => {
    if (config) setFormData(config);
  }, [config]);

  useEffect(() => {
    if (activeTab === 'orders') {
      fetchOrders();
    }
  }, [activeTab]);

  const fetchOrders = async () => {
    const { data } = await supabase
      .from('orders')
      .select('*, order_items(*)')
      .order('created_at', { ascending: false });
    setOrders(data || []);
  };

  const handleSaveConfig = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSaving(true);
    try {
      const { error } = await supabase
        .from('settings')
        .upsert({
          id: 1,
          company_name: formData.company_name,
          logo_url: formData.logo_url,
          whatsapp_number: formData.whatsapp_number,
          facebook_url: formData.facebook_url,
          instagram_url: formData.instagram_url,
          odoo_host: formData.odoo_host,
          odoo_db: formData.odoo_db,
          odoo_username: formData.odoo_username,
          odoo_api_key: formData.odoo_api_key,
          banners: formData.banners
        });

      if (error) throw error;
      setSyncStatus({msg: "Configuración guardada", type: 'success'});
      onRefresh();
    } catch (error: any) {
      setSyncStatus({msg: "Error al guardar: " + error.message, type: 'error'});
    } finally {
      setIsSaving(false);
      setTimeout(() => setSyncStatus({msg: '', type: 'none'}), 4000);
    }
  };

  const handleSync = async () => {
    setIsSyncing(true);
    setSyncStatus({msg: 'Sincronizando con Odoo...', type: 'none'});
    try {
      const result = await syncProductsFromOdoo(formData);
      setSyncStatus({msg: `¡Éxito! ${result.count} productos actualizados.`, type: 'success'});
      onRefresh();
    } catch (error: any) {
      setSyncStatus({msg: "Error: No se pudo conectar con Odoo.", type: 'error'});
    } finally {
      setIsSyncing(false);
    }
  };

  const fullSqlCode = `-- COPIA Y PEGA ESTO EN EL SQL EDITOR DE SUPABASE
-- ESTE SCRIPT CREA LAS TABLAS SI NO EXISTEN (SIN ERRORES)

-- 1. Tabla de Productos
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  odoo_id INTEGER UNIQUE,
  name TEXT NOT NULL,
  price DECIMAL(10,2) DEFAULT 0,
  qty_available INTEGER DEFAULT 0,
  image_url TEXT,
  category_name TEXT,
  default_code TEXT,
  description_sale TEXT,
  uom_name TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Configuración
CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  company_name TEXT,
  logo_url TEXT,
  whatsapp_number TEXT,
  facebook_url TEXT,
  instagram_url TEXT,
  odoo_host TEXT,
  odoo_db TEXT,
  odoo_username TEXT,
  odoo_api_key TEXT,
  banners JSONB DEFAULT '[]'
);

-- 3. Tabla de Pedidos
CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_name TEXT NOT NULL,
  customer_email TEXT,
  customer_phone TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  status TEXT DEFAULT 'pendiente',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Ítems del pedido
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  price DECIMAL(10,2) NOT NULL
);

-- 5. Insertar configuración inicial
INSERT INTO settings (id, company_name) 
VALUES (1, 'GIOFARMA') 
ON CONFLICT (id) DO NOTHING;`;

  return (
    <div className="fixed inset-0 z-[100] bg-white flex flex-col">
      <div className="bg-[#1a2b49] text-white p-6 flex justify-between items-center shadow-lg">
        <div className="flex items-center gap-4">
          <img src={formData.logo_url || LOGO_URL} className="h-10 object-contain brightness-0 invert" alt="Logo" />
          <h2 className="text-xl font-black uppercase tracking-tighter italic">Panel Administrativo</h2>
        </div>
        <button onClick={onClose} className="bg-pink-600 hover:bg-pink-700 px-6 py-2 rounded-xl font-bold text-sm transition-all">
          Cerrar Panel
        </button>
      </div>

      <div className="flex flex-grow overflow-hidden">
        {/* Sidebar */}
        <aside className="w-64 bg-gray-50 border-r border-gray-100 p-6 space-y-2">
          <button onClick={() => setActiveTab('config')} className={`w-full text-left px-4 py-3 rounded-xl font-bold text-sm flex items-center gap-3 ${activeTab === 'config' ? 'bg-pink-500 text-white shadow-lg' : 'text-gray-500 hover:bg-gray-100'}`}>
            <i className="fas fa-cog"></i> Configuración
          </button>
          <button onClick={() => setActiveTab('odoo')} className={`w-full text-left px-4 py-3 rounded-xl font-bold text-sm flex items-center gap-3 ${activeTab === 'odoo' ? 'bg-blue-600 text-white shadow-lg' : 'text-gray-500 hover:bg-gray-100'}`}>
            <i className="fas fa-sync-alt"></i> Sincronizar Odoo
          </button>
          <button onClick={() => setActiveTab('orders')} className={`w-full text-left px-4 py-3 rounded-xl font-bold text-sm flex items-center gap-3 ${activeTab === 'orders' ? 'bg-green-600 text-white shadow-lg' : 'text-gray-500 hover:bg-gray-100'}`}>
            <i className="fas fa-shopping-cart"></i> Ver Pedidos
          </button>
          <button onClick={() => setActiveTab('help')} className={`w-full text-left px-4 py-3 rounded-xl font-bold text-sm flex items-center gap-3 mt-10 ${activeTab === 'help' ? 'bg-yellow-500 text-white shadow-lg' : 'text-yellow-600 hover:bg-yellow-50'}`}>
            <i className="fas fa-code"></i> Script SQL (Ayuda)
          </button>
        </aside>

        {/* Content */}
        <main className="flex-grow p-10 overflow-y-auto">
          {syncStatus.msg && (
            <div className={`mb-6 p-4 rounded-xl font-bold text-center animate-bounce ${syncStatus.type === 'success' ? 'bg-green-100 text-green-700' : syncStatus.type === 'error' ? 'bg-red-100 text-red-700' : 'bg-blue-100 text-blue-700'}`}>
              {syncStatus.msg}
            </div>
          )}

          {activeTab === 'config' && (
            <form onSubmit={handleSaveConfig} className="max-w-3xl space-y-6">
              <h3 className="text-2xl font-black text-navy-900 mb-6">Ajustes de la Tienda</h3>
              <div className="grid grid-cols-2 gap-6">
                <div className="col-span-2">
                  <label className="block text-xs font-black text-gray-400 uppercase mb-2">Nombre Comercial</label>
                  <input type="text" value={formData.company_name} onChange={e => setFormData({...formData, company_name: e.target.value})} className="w-full p-3 bg-gray-50 border rounded-xl font-bold" />
                </div>
                <div>
                  <label className="block text-xs font-black text-gray-400 uppercase mb-2">WhatsApp de Pedidos</label>
                  <input type="text" value={formData.whatsapp_number} onChange={e => setFormData({...formData, whatsapp_number: e.target.value})} className="w-full p-3 bg-gray-50 border rounded-xl font-bold" placeholder="51900000000" />
                </div>
                <div>
                  <label className="block text-xs font-black text-gray-400 uppercase mb-2">URL del Logo</label>
                  <input type="text" value={formData.logo_url} onChange={e => setFormData({...formData, logo_url: e.target.value})} className="w-full p-3 bg-gray-50 border rounded-xl font-bold" />
                </div>
              </div>
              <button type="submit" disabled={isSaving} className="bg-[#1a2b49] text-white px-8 py-4 rounded-xl font-black uppercase text-xs tracking-widest hover:bg-pink-600 transition-all">
                {isSaving ? 'Guardando...' : 'Guardar Configuración'}
              </button>
            </form>
          )}

          {activeTab === 'odoo' && (
            <div className="max-w-3xl space-y-8">
              <h3 className="text-2xl font-black text-navy-900">Conexión con Odoo</h3>
              <div className="bg-blue-50 p-8 rounded-3xl border border-blue-100 space-y-6">
                <div className="grid grid-cols-2 gap-6">
                  <div>
                    <label className="block text-xs font-black text-blue-400 uppercase mb-2">Host Odoo</label>
                    <input type="text" value={formData.odoo_host} onChange={e => setFormData({...formData, odoo_host: e.target.value})} className="w-full p-3 bg-white border rounded-xl font-bold" />
                  </div>
                  <div>
                    <label className="block text-xs font-black text-blue-400 uppercase mb-2">Base de Datos</label>
                    <input type="text" value={formData.odoo_db} onChange={e => setFormData({...formData, odoo_db: e.target.value})} className="w-full p-3 bg-white border rounded-xl font-bold" />
                  </div>
                </div>
                <button onClick={handleSync} disabled={isSyncing} className="w-full bg-blue-600 text-white py-4 rounded-xl font-black uppercase text-xs tracking-widest flex items-center justify-center gap-3">
                  {isSyncing ? <i className="fas fa-spinner animate-spin"></i> : <i className="fas fa-sync"></i>}
                  Sincronizar Catálogo Ahora
                </button>
              </div>
            </div>
          )}

          {activeTab === 'orders' && (
            <div className="space-y-6">
              <h3 className="text-2xl font-black text-navy-900">Pedidos Recibidos</h3>
              <div className="grid gap-4">
                {orders.length === 0 ? (
                  <p className="text-gray-400 font-bold italic">No hay pedidos registrados aún.</p>
                ) : (
                  orders.map(order => (
                    <div key={order.id} className="bg-white border p-6 rounded-2xl flex justify-between items-center">
                      <div>
                        <p className="font-black text-navy-900">#{order.id.split('-')[0].toUpperCase()} - {order.customer_name}</p>
                        <p className="text-xs text-gray-400 font-bold">{order.customer_phone} | {order.customer_address}</p>
                      </div>
                      <div className="text-right">
                        <p className="text-xl font-black text-pink-600">S/ {parseFloat(order.total_amount).toFixed(2)}</p>
                        <span className="text-[10px] bg-yellow-100 text-yellow-700 px-3 py-1 rounded-full font-black uppercase">{order.status}</span>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}

          {activeTab === 'help' && (
            <div className="space-y-6">
              <h3 className="text-2xl font-black text-yellow-600">Configuración de Base de Datos</h3>
              <div className="bg-yellow-50 p-8 rounded-3xl border border-yellow-200">
                <p className="font-bold text-yellow-800 mb-4">Si ves errores al configurar Supabase, copia este código y ejecútalo en el SQL Editor:</p>
                <div className="relative">
                  <pre className="bg-white p-6 rounded-xl text-xs font-mono text-gray-600 overflow-x-auto border border-yellow-100 max-h-[400px]">
                    {fullSqlCode}
                  </pre>
                  <button onClick={() => {
                    navigator.clipboard.writeText(fullSqlCode);
                    alert("¡Copiado! Pégalo en el SQL Editor de Supabase.");
                  }} className="absolute top-4 right-4 bg-yellow-500 text-white px-4 py-2 rounded-lg font-bold text-xs shadow-lg">
                    COPIAR CÓDIGO
                  </button>
                </div>
              </div>
            </div>
          )}
        </main>
      </div>
    </div>
  );
};